server:
  port: 8092

spring:
  application:
    name: attendance-service

  datasource:
    url: jdbc:postgresql://localhost:5432/attendancedb
    username: postgres
    password: Psql#0111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
